Repository GDSC-DGU/2024-SolutionChallenge-InGlo-Server, pull requests merged in 2024-02, with the labels that each got.

#2 ✨Feat: 모델 설계
  inglo/inglo/__init__.py
  inglo/inglo/asgi.py
  inglo/inglo/settings.py
  inglo/inglo/urls.py
  inglo/inglo/wsgi.py
  inglo/issues/__init__.py
  inglo/issues/admin.py
  inglo/issues/apps.py
  inglo/issues/migrations/__init__.py
  inglo/issues/models.py
  inglo/issues/tests.py
  inglo/issues/urls.py
  inglo/issues/views.py
  inglo/manage.py
  inglo/posts/__init__.py
  inglo/posts/admin.py
  inglo/posts/apps.py
  inglo/posts/migrations/__init__.py
  inglo/posts/models.py
  inglo/posts/tests.py
  inglo/posts/urls.py
  inglo/posts/views.py
  inglo/sketches/__init__.py
  inglo/sketches/admin.py
  inglo/sketches/apps.py
  inglo/sketches/migrations/__init__.py
  inglo/sketches/models.py
  inglo/sketches/tests.py
  inglo/sketches/urls.py
  inglo/sketches/views.py
  inglo/users/__init__.py
  inglo/users/admin.py
  inglo/users/apps.py
  inglo/users/migrations/__init__.py
  inglo/users/models.py
  inglo/users/tests.py
  inglo/users/urls.py
  inglo/users/views.py
Labels: feature, 동겸

#3 ✨Feat: Make Migration
  .gitignore
  inglo/inglo/__init__.py
  inglo/inglo/settings.py
  inglo/inglo/urls.py
  inglo/issues/migrations/0001_initial.py
  inglo/issues/migrations/0002_initial.py
  inglo/posts/migrations/0001_initial.py
  inglo/posts/migrations/0002_initial.py
  inglo/posts/migrations/0003_initial.py
  inglo/sketches/migrations/0001_initial.py
  inglo/sketches/migrations/0002_initial.py
  inglo/users/migrations/0001_initial.py
Labels: fix, 동겸

#5 ✨Feat: Issue App 관련 API 구현 완료
  inglo/inglo/__init__.py
  inglo/issues/migrations/0001_initial.py
  inglo/issues/migrations/0002_initial.py
  inglo/issues/models.py
  inglo/issues/serializers.py
  inglo/issues/services/__init__.py
  inglo/issues/services/news_updater.py
  inglo/issues/urls.py
  inglo/issues/utils/__init__.py
  inglo/issues/utils/classifier.py
  inglo/issues/utils/news_api.py
  inglo/issues/views.py
  inglo/posts/migrations/0001_initial.py
  inglo/posts/migrations/0002_initial.py
  inglo/posts/migrations/0003_initial.py
  inglo/posts/serializers.py
  inglo/sketches/migrations/0001_initial.py
  inglo/sketches/migrations/0002_initial.py
  inglo/sketches/serializers.py
  inglo/users/migrations/0001_initial.py
  inglo/users/serializers.py
  inglo/users/views.py
Labels: feature, 동겸

#7 🎨 Fix: endpoints 디자인 수정
  inglo/issues/urls.py
  inglo/issues/views.py
Labels: fix, 동겸

#8 ✨Feat: 조회수 증가 로직, 좋아요 api 구현
  inglo/inglo/settings.py
  inglo/issues/migrations/0001_initial.py
  inglo/issues/migrations/0002_initial.py
  inglo/issues/models.py
  inglo/issues/serializers.py
  inglo/issues/urls.py
  inglo/issues/utils/classifier.py
  inglo/issues/utils/news_api.py
  inglo/issues/views.py
  inglo/posts/migrations/0001_initial.py
  inglo/posts/migrations/0002_initial.py
  inglo/posts/migrations/0003_initial.py
  inglo/posts/models.py
  inglo/sketches/migrations/0001_initial.py
  inglo/sketches/migrations/0002_initial.py
  inglo/users/migrations/0001_initial.py
Labels: feature, 동겸

#10 🚑 Fix: model 수정, settings.py 수정
  inglo/inglo/settings.py
  inglo/sketches/migrations/0003_crazy8content_vote_count.py
  inglo/sketches/models.py
Labels: bug, fix, 동겸

#12 🚑 Fix: Issue에 SoC 적용
  inglo/issues/permissions.py
  inglo/issues/services/comment_service.py
  inglo/issues/services/issue_services.py
  inglo/issues/services/news_updater.py
  inglo/issues/urls.py
  inglo/issues/views.py
Labels: fix, 동겸

#13 ✨Feat: 구글 소셜 로그인 구현
  inglo/accounts/__init__.py
  inglo/accounts/admin.py
  inglo/accounts/apps.py
  inglo/accounts/migrations/0001_initial.py
  inglo/accounts/migrations/__init__.py
  inglo/accounts/models.py
  inglo/accounts/tests.py
  inglo/accounts/urls.py
  inglo/accounts/views.py
  inglo/inglo/settings.py
  inglo/inglo/urls.py
  inglo/issues/migrations/0001_initial.py
  inglo/issues/migrations/0002_initial.py
  inglo/issues/models.py
  inglo/posts/migrations/0001_initial.py
  inglo/posts/migrations/0002_initial.py
  inglo/posts/models.py
  inglo/sketches/migrations/0001_initial.py
  inglo/sketches/migrations/0002_initial.py
  inglo/sketches/migrations/0003_crazy8content_vote_count.py
  inglo/sketches/models.py
  inglo/users/admin.py
  inglo/users/migrations/0001_initial.py
  inglo/users/models.py
  inglo/users/serializers.py
  inglo/users/urls.py
  inglo/users/views.py
Labels: feature, 동겸

#15 🚑 Fix: 오류 수정 및 엔드포인트 수정
  inglo/inglo/urls.py
  inglo/issues/urls.py
  inglo/issues/views.py
Labels: bug, fix, 동겸

#16 Feat: 문제정의, HMW, Crazy'8s 생성, 조회 로직
  inglo/issues/services/issue_services.py
  inglo/sketches/models.py
  inglo/sketches/serializers.py
  inglo/sketches/services/crazy8_service.py
  inglo/sketches/services/hmw_service.py
  inglo/sketches/services/problem_service.py
  inglo/sketches/urls.py
  inglo/sketches/views.py
Labels: feature, 동겸

#17 ✨Feat: Crazy8's 투표 api 구현
  inglo/sketches/models.py
  inglo/sketches/services/crazy8_service.py
  inglo/sketches/views.py
Labels: feature, 동겸

#20 ✨Feat: Sketch 삭제 api 구현
  inglo/sketches/services/sketch_service.py
  inglo/sketches/views.py
Labels: feature, 동겸

#21 ✨Feat: Sketch 상세보기 api 구현
  inglo/sketches/serializers.py
  inglo/sketches/services/sketch_service.py
  inglo/sketches/urls.py
  inglo/sketches/views.py
Labels: feature, 동겸

#22 ✨Feat: 포스트, 포스트의 피드백 관련 api 1차 구현 완료
  inglo/issues/services/issue_services.py
  inglo/posts/models.py
  inglo/posts/serializers.py
  inglo/posts/services/feedback_service.py
  inglo/posts/services/post_service.py
  inglo/posts/urls.py
  inglo/posts/views.py
Labels: feature, 동겸

#24 🐛Fix: Sketch 관련 API 테스팅 진행사항 중 오류 수정
  inglo/accounts/migrations/0001_initial.py
  inglo/accounts/templates/accounts/login_success.html
  inglo/accounts/urls.py
  inglo/accounts/views.py
  inglo/inglo/settings.py
  inglo/issues/migrations/0001_initial.py
  inglo/posts/migrations/0001_initial.py
  inglo/posts/models.py
  inglo/posts/serializers.py
  inglo/posts/urls.py
  inglo/sketches/admin.py
  inglo/sketches/migrations/0001_initial.py
  inglo/sketches/migrations/0002_crazy8content_created_at_crazy8stack_created_at_and_more.py
  inglo/sketches/models.py
  inglo/sketches/serializers.py
  inglo/sketches/services/crazy8_service.py
  inglo/sketches/services/problem_service.py
  inglo/sketches/services/sketch_service.py
  inglo/sketches/views.py
Labels: bug, fix, 동겸

#25 🐛Fix: Issue 관련 API 테스팅 진행사항 중 오류 수정
  inglo/issues/admin.py
  inglo/issues/migrations/0002_alter_issue_image_url_alter_issue_writer.py
  inglo/issues/migrations/0003_alter_issue_writer.py
  inglo/issues/migrations/0004_alter_issuelist_description.py
  inglo/issues/models.py
  inglo/issues/serializers.py
  inglo/issues/services/comment_service.py
  inglo/issues/urls.py
  inglo/issues/views.py
Labels: bug, fix, 동겸

#26 🐛Fix: Post 관련 API 테스팅 진행사항 중 오류 수정
  inglo/posts/admin.py
  inglo/posts/migrations/0002_alter_post_likes.py
  inglo/posts/migrations/0003_post_title.py
  inglo/posts/models.py
  inglo/posts/serializers.py
  inglo/posts/services/feedback_service.py
  inglo/posts/services/post_service.py
  inglo/posts/views.py
Labels: bug, fix, 동겸

#28 ✨Feat: userinfo 조회 api 구현
  inglo/accounts/migrations/0002_user_profile_img.py
  inglo/accounts/models.py
  inglo/accounts/serializers.py
  inglo/accounts/urls.py
  inglo/accounts/views.py
  inglo/issues/serializers.py
  inglo/issues/urls.py
  inglo/issues/views.py
Labels: feature, 동겸

#29 🚑 Fix: 구글 소셜로그인 로직 수정, 이슈 리스트에 이미지 같이 넘기도록 수정
  inglo/accounts/templates/accounts/login_success.html
  inglo/accounts/urls.py
  inglo/accounts/views.py
  inglo/inglo/settings.py
  inglo/issues/migrations/0005_issuelist_image_url.py
  inglo/issues/models.py
  inglo/issues/services/issue_services.py
Labels: fix, 동겸

#30 ✨Feat: 유저 관련 로그인, 회원가입, 마이페이지 API 뷰 완성
  inglo/accounts/migrations/0003_user_additional_info_provided_user_name_and_more.py
  inglo/accounts/migrations/0004_user_global_impact_user_post_total.py
  inglo/accounts/models.py
  inglo/accounts/serializers.py
  inglo/accounts/services/user_service.py
  inglo/accounts/urls.py
  inglo/accounts/views.py
  inglo/issues/urls.py
  inglo/posts/urls.py
  inglo/posts/views.py
  inglo/sketches/urls.py
  inglo/sketches/views.py
Labels: feature, fix, 동겸

#31 ✨Feat: 이미지 업로드 S3 이용하는 로직 추가, 뷰셋 변환
  inglo/issues/services/issue_services.py
  inglo/issues/urls.py
  inglo/issues/views.py
  inglo/posts/models.py
  inglo/posts/serializers.py
  inglo/posts/services/feedback_service.py
  inglo/posts/services/post_service.py
  inglo/posts/urls.py
  inglo/posts/views.py
  inglo/sketches/services/sketch_service.py
  inglo/sketches/urls.py
  inglo/sketches/views.py
Labels: feature, fix, 동겸

#32 🐛Fix: IssueComment 관련 url Mapping 안되던 오류 수정
  inglo/accounts/views.py
  inglo/issues/services/comment_service.py
  inglo/issues/views.py
Labels: bug, fix, 동겸

#34 🐛 ✨ hmw 선택 api 구현, 포스트 수정 시 이미지 추가 가능 및 각종 오류 수정
  inglo/accounts/urls.py
  inglo/accounts/views.py
  inglo/posts/migrations/0004_post_image_url.py
  inglo/posts/serializers.py
  inglo/posts/services/post_service.py
  inglo/posts/views.py
  inglo/sketches/migrations/0003_alter_sketch_crazy8stack_alter_sketch_hmw_and_more.py
  inglo/sketches/models.py
  inglo/sketches/services/hmw_service.py
  inglo/sketches/urls.py
  inglo/sketches/views.py
Labels: bug, feature, fix, 동겸

#35 🚑 Fix: 소셜로그인 배포 환경용 api로 변경
  inglo/accounts/urls.py
  inglo/accounts/views.py
Labels: fix, 동겸

#37 🚑 무한 리다이렉션 해결
  inglo/inglo/settings.py
Labels: bug, fix, 동겸

#38 🚑 CRSF 설정 변경
  inglo/inglo/settings.py
Labels: bug, fix, 동겸

#41 ✨API 테스팅 중 수정사항 및 개선사항 반영
  Dockerfile
  inglo/accounts/serializers.py
  inglo/issues/migrations/0006_alter_issuelist_country.py
  inglo/issues/migrations/0007_issue_article_id.py
  inglo/issues/migrations/0008_remove_issue_article_id.py
  inglo/issues/models.py
  inglo/issues/serializers.py
  inglo/issues/services/issue_services.py
  inglo/issues/utils/classifier.py
  inglo/issues/utils/news_api.py
  inglo/posts/migrations/0002_remove_post_image_url.py
  inglo/posts/models.py
  inglo/posts/serializers.py
  inglo/posts/services/post_service.py
  inglo/posts/views.py
  inglo/sketches/serializers.py
Labels: bug, feature, fix, 동겸

#43 ✨ 각종 요구사항 반영
  inglo/accounts/migrations/0002_user_refresh_token.py
  inglo/accounts/models.py
  inglo/accounts/serializers.py
  inglo/accounts/services/user_service.py
  inglo/accounts/urls.py
  inglo/accounts/views.py
  inglo/inglo/settings.py
  inglo/issues/serializers.py
  inglo/issues/utils/classifier.py
  inglo/issues/utils/model.py
  inglo/issues/utils/news_api.py
  inglo/issues/utils/predict.py
  inglo/posts/serializers.py
  inglo/posts/services/feedback_service.py
  inglo/posts/urls.py
  inglo/posts/views.py
  inglo/sketches/migrations/0002_crazy8content_user_crazy8stack_user_hmw_user_and_more.py
  inglo/sketches/migrations/0003_remove_crazy8content_user_remove_crazy8stack_user_and_more.py
  inglo/sketches/migrations/0004_alter_sketch_user.py
  inglo/sketches/models.py
  inglo/sketches/serializers.py
  inglo/sketches/services/crazy8_service.py
  inglo/sketches/services/problem_service.py
  inglo/sketches/services/sketch_service.py
  inglo/sketches/urls.py
  inglo/sketches/views.py
Labels: feature, 동겸

#45 ✨예외 처리 추가
  inglo/accounts/urls.py
  inglo/accounts/views.py
  inglo/inglo/settings.py
  inglo/issues/services/comment_service.py
  inglo/issues/services/issue_services.py
  inglo/issues/urls.py
  inglo/issues/views.py
  inglo/posts/services/feedback_service.py
  inglo/posts/services/post_service.py
  inglo/posts/views.py
  inglo/sketches/services/crazy8_service.py
  inglo/sketches/services/hmw_service.py
  inglo/sketches/services/problem_service.py
  inglo/sketches/services/sketch_service.py
  inglo/sketches/views.py
Labels: feature, fix, 동겸

#47 🚑 fix: 분류모델 경로 수정 및 로깅 추가
  inglo/issues/services/issue_services.py
  inglo/issues/utils/classifier.py
  inglo/issues/utils/news_api.py
Labels: bug, fix, 동겸

#48 fix: 1024 token limit
  inglo/issues/utils/classifier.py
  inglo/issues/utils/predict.py
Labels: bug, fix, 현진

#49 🖊️docs: modify requirements.txt
  requirements.txt
Labels: 동겸

#50 분류모델 테스트 완료
  inglo/inglo/settings.py
Labels: bug, fix, 동겸

#51 ✨ 이슈 생성 api를 서버에서 스케쥴링하여 시간마다 호출하도록 구현
  Dockerfile
  cronjob
  entrypoint.sh
  inglo/call_issue_create_api.py
  inglo/inglo/settings.py
  inglo/issues/decorators/allow_server_ip_only.py
  inglo/issues/views.py
Labels: feature, 동겸

#52 🐛 Fix: 스케쥴링 제대로 진행 안되던 오류 수정, 이슈 추가될때 중복된 이슈 추가 안하도록 수정, 비어있는 스케치는 불러오지 않도록 수정
  cronjob
  inglo/issues/services/issue_services.py
  inglo/sketches/services/sketch_service.py
Labels: bug, fix, 동겸

#53 🐛fix: 외부 ip에서도 이슈 생성 api가 호출되는 버그 발견. 임시 조치
  inglo/issues/decorators/allow_server_ip_only.py
Labels: bug, 동겸

#54 🐛 fix: 내 서버에서만 api 요청 보내도록 수정
  inglo/issues/decorators/allow_server_ip_only.py
  inglo/issues/views.py
Labels: fix, 동겸
